appName: nginx

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.14.2

containerPort: 80

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http