{{- if .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-booster.fullname" . }}
  labels:
    {{- include "generic-booster.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.configMaps }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end }}