apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-cronjob.fullname" . }}
  labels:
    {{- include "generic-cronjob.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  annotations: {}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- toYaml .Values.jobLabels | nindent 8 }}
      annotations:
        {{- toYaml .Values.jobAnnotations | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      {{- if gt .Values.ttlSecondsAfterFinished -1.0 }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          annotations:
            {{- include "generic-cronjob.podAnnotations" . | nindent 12 }}
          labels:
            {{- include "generic-cronjob.podLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "generic-cronjob.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
          - name: {{ .Values.appName | default .Release.Name }}
            {{- if or .Values.containerSecurityContext }}
            securityContext:
              {{- toYaml .Values.containerSecurityContext | nindent 14 }}
            {{- end }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.env }}
            env:
              {{- toYaml .Values.env | nindent 14 }}
              {{- if .Values.extraEnv }}
              {{- toYaml .Values.extraEnv | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.command }}
            command:
              {{- toYaml .Values.command | nindent 14 }}
              {{- if .Values.extraCommand }}
              {{- toYaml .Values.extraCommand | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.args }}
            args:
              {{- toYaml .Values.args | nindent 14 }}
              {{- if .Values.extraArgs }}
              {{- toYaml .Values.extraArgs | nindent 14 }}
              {{- end }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.volumes }}
          volumes:
            {{- toYaml .Values.volumes | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumes }}
          extraVolumes:
            {{- toYaml .Values.extraVolumes | nindent 12 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraContainers }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 3
  suspend: {{ .Values.suspend }}
