{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-booster.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: 
{{- range $path, $config := .data }}
  {{ $path }}: |
{{ (tpl $config $) | indent 4 -}}
{{- end }}
{{- end }}
