{{- if or (eq .Values.resource_type "deploy") (eq .Values.resource_type "deployment") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-booster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-booster.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
{{- if and (not .Values.autoscaling.enabled) (ge .Values.replicaCount 0.0) }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- if .Values.matchLabels }}
      {{- toYaml .Values.matchLabels | nindent 6 }}
      {{- else }}
      {{- include "generic-booster.matchLabels" . | nindent 6 }}
      {{- end }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "generic-booster.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "generic-booster.podLabels" . | nindent 8 }}
        {{- if .Values.datadog.enabled }}
        {{- include "generic-booster.datadogLabels" . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-booster.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      {{- if and (.Values.datadog.enabled) (eq .Values.datadog.language "java") }}
      - name: datadog-apm-agent
        # busybox로 하면 tls 에러가 날때가 있어 alpine으로 변경
        # 같은 이미지로 하여도 dev에서는 안나고, prod에서만 발생
        # image: busybox
        image: public.ecr.aws/docker/library/alpine
        imagePullPolicy: IfNotPresent
        command:
        - wget
        - -O
        - /datadog/apm/agent/dd-java-agent.jar
        - https://dtdg.co/latest-java-tracer
        volumeMounts:
        - name: datadog-apm-agent
          mountPath: /datadog/apm/agent
      {{- end }}
      containers:
        - name: {{ .Values.appName | default .Release.Name }}
          {{- if or .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.env }}
          {{- include "generic-booster.env" . | nindent 12 }}
          {{- end }}
          {{- if .Values.extraEnv }}
          {{- include "generic-booster.extraEnv" . | nindent 12 }}
          {{- end }}
          {{- if .Values.datadog.enabled }}
          {{- include "generic-booster.datadogEnv" . | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command:
          {{- toYaml .Values.command | nindent 12 }}
          {{- if .Values.extraCommand }}
          {{- toYaml .Values.extraCommand | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.args }}
          args:
          {{- toYaml .Values.args | nindent 12 }}
          {{- if .Values.extraArgs }}
          {{- toYaml .Values.extraArgs | nindent 12 }}
          {{- end}}
          {{- end}}
          ports:
            {{- toYaml .Values.containerPorts | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
          {{- if and (.Values.datadog.enabled) (eq .Values.datadog.language "java") }}
          - name: datadog-apm-agent
            mountPath: /datadog/apm/agent
          {{- end }}
          {{- if .Values.tty }}
          tty: true
          {{- end }}
          {{- if .Values.extraContainerAttrs }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if and (.Values.datadog.enabled) (eq .Values.datadog.language "java") }}
      - name: datadog-apm-agent
        emptyDir: {}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.extraContainers }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}