{{ $vs := .Values.virtualServicePreview }}
{{- if .Values.istio.enabled }}
{{- if $vs.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "generic-booster.fullname" . }}-preview
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $vs.labels | toYaml | nindent 4 }}
  annotations:
    {{- $vs.annotations | toYaml | nindent 4 }}
spec:
  gateways:
  {{- if $vs.gateways }}
  {{- $vs.gateways | toYaml | nindent 2 }}
  {{- else }}
  - {{ $.Release.Namespace }}-ext
  {{- end }}
  hosts:
  {{- $vs.hosts | toYaml | nindent 2 }}
  http:
  {{- if $vs.http }}
  {{- $vs.http | toYaml | nindent 2 }}
  {{- else }}
  - name: preview
    route:
    - destination:
        host: {{ include "generic-booster.fullname" . }}
        subset: canary
      weight: 100
  {{- end }}
{{- end }}
{{- end }}