{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-booster.serviceName" . }}
  labels:
    {{- include "generic-booster.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not (eq .Values.service.clusterIP "None") }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if not (eq .Values.service.clusterIP "") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    {{- if not .Values.service.ports }}
    - port: 80
      targetPort: "http"
      protocol: "TCP"
      name: "http"
    {{- else }}
    {{- toYaml .Values.service.ports | trim | nindent 4 }}
    {{- end }}
  selector:
    {{- include "generic-booster.serviceSelectorLabels" . | nindent 4 }}
{{- end }}
